global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vigil-crawler'
    static_configs:
      - targets: ['vigil-crawler:3010']

  - job_name: 'vigil-transaction-runner'
    static_configs:
      - targets: ['vigil-transaction-runner:3011']

  - job_name: 'vigil-alert-manager'
    static_configs:
      - targets: ['vigil-alert-manager:3012']

  - job_name: 'vigil-api'
    static_configs:
      - targets: ['vigil-api:3013']
